// Bilingual content for Emer Värk site (ET / EN)
window.CONTENT = {
  et: {
    nav: {
      home: "Avaleht",
      about: "Minust",
      services: "Teenused",
      portfolio: "Töid",
      contact: "Kontakt",
      book: "Tutvumisvestlus →",
    },
    meta: {
      tagline: "AI visuaalproduktsioonis · 2024 →",
      based: "Eestis · töötab Põhjamaades",
      role: "Visuaalkunstnik · Animaator · AI-praktik",
    },
    home: {
      heroLine1: "AI visuaalproduktsioonis.",
      heroLine2: "Kunstniku silmaga.",
      heroSub: "Õpetan loovagentuure ja brändimeeskondi, kuidas saada AI-st visuaalset sisu, mida saab avaldada — mitte sellist, mille klient saadab tagasi.",
      ctaPrimary: "Vaata teenuseid",
      ctaSecondary: "Tutvumisvestlus, 30 min",
      indexTitle: "Sisukord",
      sections: [
        { n: "01", t: "Avaleht" },
        { n: "02", t: "Miks teistsugune" },
        { n: "03", t: "Teenused" },
        { n: "04", t: "Töid" },
        { n: "05", t: "Minust" },
        { n: "06", t: "Kontakt" },
      ],
      whyTitle: "Miks teistsugune",
      whyKicker: "Kolm asja, mis teevad vahet",
      why: [
        {
          n: "01",
          k: "Taust",
          t: "Kunsti-, mitte turundustaust",
          b: "Enamus AI-koolitajaid Eestis tulevad turunduse, müügi või tehnoloogia maailmast. Mina tulen visuaalproduktsioonist — live-eventidelt, immersiivlavastusest, kontserdivisuaalidest. See tähendab, et tunnen pildi keelt: kompositsioon, värv, kontrast, rütm.",
        },
        {
          n: "02",
          k: "Praktika",
          t: "Praktik, mitte demonstreerija",
          b: "Kasutan AI-tööriistu päris produktsioonis: Phoenix Immersive Riias, OP Pank Kumus, Veteranirock visualid, festivaliprojektsioonid. Mitte ei räägi tulevikust — räägin sellest, mis töötas eile öösel laval ja mis ei töötanud.",
        },
        {
          n: "03",
          k: "Stack",
          t: "Kogu pildi- ja video-AI maastik",
          b: "ComfyUI, custom LoRA / LoKr treenimine, image-to-video (Runway, Kling, Veo), Nanobanana, Ideogram, Flux, Midjourney, fal.ai, TouchDesigner. Mitte ainult ChatGPT ja Canva. Tunnen, milline tööriist millise probleemi jaoks ja millal mitte ühtegi neist.",
        },
      ],
      servicesPreviewTitle: "Teenused",
      servicesPreviewKicker: "Hinnad on stardihinnad esimeseks 6 kuuks",
      servicesAll: "Kõik teenused →",
      portfolioPreviewTitle: "Valik töid",
      portfolioPreviewKicker: "Live-event · immersive · custom mudelid",
      portfolioAll: "Kogu portfoolio →",
      processTitle: "Tööprotsess",
      processKicker: "Neli sammu, ei rohkem",
      footerCta: "Tahad kvaliteediga AI-visuaali, mida saab avaldada?",
      footerCtaSub: "Broneeri 30 min vestlus. Tasuta. Ütlen ausalt, kas sobivus on.",
    },
    services: [
      {
        idx: "S/01",
        name: "Töötuba «AI loomeprotsessis»",
        format: "1 päev kohapeal · kuni 8 inimest",
        price: "€2200–2800",
        unit: "+ km",
        for: "Loovagentuurid, brändimeeskonnad",
        body: "Eelnev 45-min vajaduste kaart. 6 h aktiivset töötuba. Kohandatud workflow-dokument. Prompt-raamat (50+). Tööriistastacki seadistus. 4-nädala järeltugi (2× 1 h Zoom + e-mail). 1 redigeerimisring.",
      },
      {
        idx: "S/02",
        name: "Workflow-disain",
        format: "projektipõhine konsultatsioon · 2–4 nädalat",
        price: "€4500–8000",
        unit: "+ km",
        for: "Konkreetne kampaania, tooteliin, produktsioon",
        body: "Disainin AI-workflow konkreetse vajaduse jaoks ja treenin 1–2 inimest seda kasutama. Iseseisvalt töövõimeline tiim 3 nädalaga.",
      },
      {
        idx: "S/03",
        name: "Brändi pildi-stiili LoRA",
        format: "custom mudel + 4 h koolitust",
        price: "€2000–3500",
        unit: "+ km",
        for: "Brändid, kelle visuaalne keel peab olema järjepidev",
        body: "Klient saab oma brändi visuaalses keeles treenitud pildimudeli (LoRA / SDXL / Flux). Tulemus: brändijoon hoitakse igas AI-genereeritud pildis.",
      },
      {
        idx: "S/04",
        name: "1-1 mentorlus loovjuhtidele",
        format: "6 sessiooni × 90 min",
        price: "€1200–1800",
        unit: "+ km",
        for: "Loovjuhid, kes vastutavad AI-strateegia eest",
        body: "Individuaalne workflow-i ülesehitus, privaatne prompt-raamat, jätku-Slack-tugi.",
      },
      {
        idx: "S/05",
        name: "Custom konsultatsioon",
        format: "tunnipõhine · min 2 h",
        price: "€150 / h",
        unit: "+ km",
        for: "Kiired küsimused, audit, tööriista-tugi",
        body: "Workflow-audit, tööriistaspetsiifiline tugi, kiired produktsiooniprobleemid.",
      },
    ],
    portfolio: [
      {
        idx: "W/01",
        year: "2024",
        title: "Phoenix Immersive — Van Gogh",
        loc: "Riia, LV",
        role: "Sisuspetsifikatsioon · operaatori paigutus",
        stack: ["disguise GX 3", "360° projection mapping", "PoCo Experience"],
        size: "lg",
        tags: ["live-event", "immersive"],
      },
      {
        idx: "W/02",
        year: "2024",
        title: "OP Pank — Kumu auditoorium",
        loc: "Tallinn, EE",
        role: "Kontseptsioon · animatsioon · kunstiline juhtimine",
        stack: ["Kahekihiline projektsioon", "Scrim + tagaekraan", "After Effects"],
        size: "md",
        tags: ["av-installation"],
      },
      {
        idx: "W/03",
        year: "2024",
        title: "Veteranirock",
        loc: "Tallinn, EE",
        role: "Visuaaloperaator · sisuplaanid",
        stack: ["Vanilla Ninja", "5MIINUST", "Resolume"],
        size: "sm",
        tags: ["concert"],
      },
      {
        idx: "W/04",
        year: "2025",
        title: "ACE-Step 1.5 XL Turbo",
        loc: "Personal LoKr training",
        role: "Custom mudel · raster-noton stiil",
        stack: ["RTX 4080 SUPER", "27-näidisline andmestik", "Alva Noto"],
        size: "md",
        tags: ["custom-model", "audio-ai"],
      },
      {
        idx: "W/05",
        year: "2025",
        title: "Tark Reklaamekraan",
        loc: "Piletilevi, EE",
        role: "Computer vision · külastajatuvastus",
        stack: ["Raspberry Pi 5", "YOLO", "DeepFace"],
        size: "sm",
        tags: ["computer-vision"],
      },
      {
        idx: "W/06",
        year: "2024",
        title: "Festivali-projektsioonid",
        loc: "EE / FI",
        role: "Kontseptsioon · live-operaator",
        stack: ["TouchDesigner", "Notch", "Resolume"],
        size: "lg",
        tags: ["festival", "live"],
      },
      {
        idx: "W/07",
        year: "2025",
        title: "Custom LoRA — kontserdiplakatid",
        loc: "EE",
        role: "Brändi-stiili mudel",
        stack: ["Flux", "ComfyUI", "image-to-video"],
        size: "md",
        tags: ["lora", "branding"],
      },
    ],
    process: [
      {
        n: "01",
        t: "Tutvumisvestlus",
        d: "30 min, tasuta",
        b: "Mis on teie tegelik vajadus? Praegune workflow, valupunktid, mahuvajadus, brändijoon. Kui pole sobivust — ütlen ausalt.",
      },
      {
        n: "02",
        t: "Vajaduste kaart ja pakkumine",
        d: "1 nädal",
        b: "Saatke 1–2 näidet praegusest visuaalsisust. Tagastan konkreetse pakkumise: mis koolitus / projekt, mis tulemus, mis hind, mis ajakava.",
      },
      {
        n: "03",
        t: "Töö ise",
        d: "1 päev kuni 4 nädalat",
        b: "Töötuba kohapeal, workflow-ehitus, mudeli treenimine või kombineeritud. Igal sammul nähtav vaheresultaat.",
      },
      {
        n: "04",
        t: "Järeltugi",
        d: "4 nädalat",
        b: "Kõik teenused sisaldavad järeltuge. Te ei jää koolitusega üksi, kui tulevad reaalse rakendamise küsimused.",
      },
    ],
    about: {
      kicker: "Minust",
      lead: "Vabakutseline visuaalkunstnik, animaator, loovjuht ja video-operaator/-tehnik. Töötan Eestis ja Põhjamaades.",
      bio: [
        "Olen tegutsenud Eesti elavlavalisel ja kontsertvisuaalproduktsiooni alal aastaid — kontseptsioon, animatsioon, kunstiline juhtimine, kohapealne operaator. Viimase aasta olen integreerinud AI-tööriistu päris produktsiooni: mis töötab laval, mis on demos hea aga produktsioonis kasutu, kuidas hoida brändijoont AI-genereeritud sisul, kuidas treenida custom mudeleid eristuva visuaalse keele jaoks.",
        "Õpetamist olen teinud ka varem — loengud kunsti- ja muusikakoolides, AI kunstis loengud noortele. Kõige tugevam asi koolitajana: ma tean, kuidas pilti üles ehitada enne kui ma tean, kuidas tööriista kasutada. See järjekord teeb vahet.",
      ],
      stackTitle: "Tehnilised tööriistad",
      stack: [
        { g: "Lokaalne", items: ["ComfyUI (RTX 4080 SUPER)", "Custom LoRA / LoKr / SDXL / Flux", "ACE-Step (audio-AI)"] },
        { g: "Live-event", items: ["disguise media-server", "Notch", "Resolume", "TouchDesigner (sh MCP)"] },
        { g: "Pilt & video", items: ["Runway ML · Kling · Google Veo", "fal.ai · Nanobanana · Ideogram", "Adobe suite"] },
      ],
      whatTitle: "Kus mind võib näha",
      what: [
        { n: "—", t: "PoCo Experience", d: "Professionaalne immersiivse eventi-tehnoloogia" },
        { n: "—", t: "Loengud kunstikoolides", d: "AI kunstis, noortele" },
        { n: "—", t: "Vabakutseline", d: "Eesti & Põhjamaad" },
      ],
    },
    contact: {
      kicker: "Kontakt",
      title: "Tutvumisvestlus.",
      title2: "30 minutit.",
      title3: "Tasuta.",
      lead: "Mis on teie tegelik vajadus? Praegune workflow, valupunktid, mahuvajadus, brändijoon. Kui pole sobivust — ütlen ausalt.",
      book: "Broneeri kalendrist",
      channels: [
        { l: "E-mail", v: "emer@example.ee" },
        { l: "LinkedIn", v: "linkedin.com/in/emervärk" },
        { l: "Instagram", v: "@emer.värk" },
      ],
      not: [
        "Ei mingit Facebook-Messenger'it",
        "Ei mingit live-chat widgetit",
        "Ei mingit «free download» pop-up'i",
      ],
      faq: [
        {
          q: "Kas see sobib turundajatele, kellel pole kunsti-tausta?",
          a: "Sobib — selle koolituse mõte ongi kalibreerida turundaja silma. Te ei pea ise kunstnikuks saama, aga oskate eristada, miks üks AI-pilt töötab ja teine ei.",
        },
        {
          q: "Kas õpetate ka ChatGPT-d ja tekstiloomet?",
          a: "Vaid niivõrd, kui see toetab visuaalset workflow-d. Üldiseks ChatGPT-koolitusteks soovitan AI Eesti või Kasulik AI.",
        },
        {
          q: "Mis tööriistu õpetate?",
          a: "Sõltub teie vajadusest. Tüüpiliselt: ComfyUI lokaalseks tööks, Midjourney / Flux / Nanobanana piltideks, Runway / Kling / Veo videoks, Ideogram tekst-piltideks.",
        },
        {
          q: "Kas toimub eesti või inglise keeles?",
          a: "Mõlemas. Eestis tavaliselt eesti keeles, Põhjamaades inglise keeles.",
        },
        {
          q: "Kas pakute ka tegelikku produktsiooniteenust?",
          a: "Olen primaarselt produktsiooniinimene, kes ka koolitab. Suuremate produktsiooniprojektide jaoks PoCo Experience kaudu.",
        },
      ],
    },
    foot: {
      colophon: "Saidi pildikeel ja kood —",
      author: "Emer Värk, 2026",
      tech: "ET · EN · monospace · ei mingit Google Analytics",
    },
  },
  en: {
    nav: {
      home: "Index",
      about: "About",
      services: "Services",
      portfolio: "Work",
      contact: "Contact",
      book: "Book a call →",
    },
    meta: {
      tagline: "AI in visual production · 2024 →",
      based: "Based in Estonia · works in the Nordics",
      role: "Visual artist · Animator · AI practitioner",
    },
    home: {
      heroLine1: "AI in visual production.",
      heroLine2: "With an artist's eye.",
      heroSub: "I teach creative agencies and brand teams how to get visual content out of AI that you can actually publish — not the kind clients send back.",
      ctaPrimary: "See services",
      ctaSecondary: "30-min intro call",
      indexTitle: "Index",
      sections: [
        { n: "01", t: "Index" },
        { n: "02", t: "Why it's different" },
        { n: "03", t: "Services" },
        { n: "04", t: "Work" },
        { n: "05", t: "About" },
        { n: "06", t: "Contact" },
      ],
      whyTitle: "Why it's different",
      whyKicker: "Three things that make a difference",
      why: [
        {
          n: "01",
          k: "Background",
          t: "From art, not marketing",
          b: "Most AI trainers in Estonia come from marketing, sales or tech. I come from visual production — live events, immersive shows, concert visuals. That means I know the language of the image: composition, color, contrast, rhythm. The AI tool alone doesn't know these — a trained eye plus the tool does.",
        },
        {
          n: "02",
          k: "Practice",
          t: "Practitioner, not demonstrator",
          b: "I use AI tools in real production: Phoenix Immersive in Riga, OP Bank at Kumu, Veteranirock visuals, festival projections. I don't talk about the future — I talk about what worked on stage last night and what didn't.",
        },
        {
          n: "03",
          k: "Stack",
          t: "The whole image- and video-AI landscape",
          b: "ComfyUI, custom LoRA / LoKr training, image-to-video (Runway, Kling, Veo), Nanobanana, Ideogram, Flux, Midjourney, fal.ai, TouchDesigner. Not just ChatGPT and Canva. I know which tool for which problem, and when none of them.",
        },
      ],
      servicesPreviewTitle: "Services",
      servicesPreviewKicker: "Starter rates for the first 6 months",
      servicesAll: "All services →",
      portfolioPreviewTitle: "Selected work",
      portfolioPreviewKicker: "Live event · immersive · custom models",
      portfolioAll: "Full portfolio →",
      processTitle: "Process",
      processKicker: "Four steps. No more.",
      footerCta: "Want quality AI visuals you can actually publish?",
      footerCtaSub: "Book a 30-min call. Free. I'll tell you honestly if it's a fit.",
    },
    services: [
      {
        idx: "S/01",
        name: "Workshop «AI in the creative process»",
        format: "1 day on-site · up to 8 people",
        price: "€2200–2800",
        unit: "+ VAT",
        for: "Creative agencies, brand teams",
        body: "45-min needs mapping call. 6 h active workshop. Custom workflow document. Prompt book (50+). Tool-stack setup. 4-week aftercare (2× 1 h Zoom + email). 1 revision round.",
      },
      {
        idx: "S/02",
        name: "Workflow design",
        format: "project consultation · 2–4 weeks",
        price: "€4500–8000",
        unit: "+ VAT",
        for: "A specific campaign, product line, production",
        body: "I design the AI workflow for your specific need and train 1–2 people to run it. Independent team in 3 weeks.",
      },
      {
        idx: "S/03",
        name: "Brand image-style LoRA",
        format: "custom model + 4 h training",
        price: "€2000–3500",
        unit: "+ VAT",
        for: "Brands whose visual language must be consistent",
        body: "You get a model trained on your brand's visual language (LoRA / SDXL / Flux). Result: brand consistency in every AI-generated image.",
      },
      {
        idx: "S/04",
        name: "1-1 mentoring for creative directors",
        format: "6 sessions × 90 min",
        price: "€1200–1800",
        unit: "+ VAT",
        for: "Creative directors owning AI strategy",
        body: "Individual workflow build, private prompt book, ongoing Slack support.",
      },
      {
        idx: "S/05",
        name: "Custom consultation",
        format: "hourly · min 2 h",
        price: "€150 / h",
        unit: "+ VAT",
        for: "Quick questions, audits, tool support",
        body: "Workflow audit, tool-specific support, fast production problems.",
      },
    ],
    portfolio: [
      {
        idx: "W/01",
        year: "2024",
        title: "Phoenix Immersive — Van Gogh",
        loc: "Riga, LV",
        role: "Content spec · operator setup",
        stack: ["disguise GX 3", "360° projection mapping", "PoCo Experience"],
        size: "lg",
        tags: ["live-event", "immersive"],
      },
      {
        idx: "W/02",
        year: "2024",
        title: "OP Bank — Kumu auditorium",
        loc: "Tallinn, EE",
        role: "Concept · animation · art direction",
        stack: ["Two-layer projection", "Scrim + back-screen", "After Effects"],
        size: "md",
        tags: ["av-installation"],
      },
      {
        idx: "W/03",
        year: "2024",
        title: "Veteranirock",
        loc: "Tallinn, EE",
        role: "Visual operator · content plans",
        stack: ["Vanilla Ninja", "5MIINUST", "Resolume"],
        size: "sm",
        tags: ["concert"],
      },
      {
        idx: "W/04",
        year: "2025",
        title: "ACE-Step 1.5 XL Turbo",
        loc: "Personal LoKr training",
        role: "Custom model · raster-noton style",
        stack: ["RTX 4080 SUPER", "27-sample dataset", "Alva Noto"],
        size: "md",
        tags: ["custom-model", "audio-ai"],
      },
      {
        idx: "W/05",
        year: "2025",
        title: "Smart Ad Screen",
        loc: "Piletilevi, EE",
        role: "Computer vision · viewer detection",
        stack: ["Raspberry Pi 5", "YOLO", "DeepFace"],
        size: "sm",
        tags: ["computer-vision"],
      },
      {
        idx: "W/06",
        year: "2024",
        title: "Festival projections",
        loc: "EE / FI",
        role: "Concept · live operator",
        stack: ["TouchDesigner", "Notch", "Resolume"],
        size: "lg",
        tags: ["festival", "live"],
      },
      {
        idx: "W/07",
        year: "2025",
        title: "Custom LoRA — concert posters",
        loc: "EE",
        role: "Brand-style model",
        stack: ["Flux", "ComfyUI", "image-to-video"],
        size: "md",
        tags: ["lora", "branding"],
      },
    ],
    process: [
      {
        n: "01",
        t: "Intro call",
        d: "30 min, free",
        b: "What's your real need? Current workflow, pain points, volume, brand voice. If it's not a fit — I'll say so honestly.",
      },
      {
        n: "02",
        t: "Needs map and proposal",
        d: "1 week",
        b: "Send 1–2 examples of current visual content. I return a concrete proposal: which training / project, what result, what price, what timeline.",
      },
      {
        n: "03",
        t: "The work itself",
        d: "1 day to 4 weeks",
        b: "On-site workshop, workflow build, model training, or combined. Visible interim results at every step.",
      },
      {
        n: "04",
        t: "Aftercare",
        d: "4 weeks",
        b: "All services include aftercare. You're not alone with the training when real implementation questions show up.",
      },
    ],
    about: {
      kicker: "About",
      lead: "Freelance visual artist, animator, art director and video operator/technician. Works in Estonia and the Nordics.",
      bio: [
        "I've worked in Estonian live-stage and concert visual production for years — concept, animation, art direction, on-site operator. For the past year I've been integrating AI tools into real production: what works on stage, what looks good in a demo but is useless in production, how to keep brand consistency in AI-generated content, how to train custom models for a distinctive visual language.",
        "I've taught before too — lectures at art and music schools, AI-in-art talks for young people. The strongest thing about me as a trainer: I know how to build an image before I know how to use the tool. That order makes the difference.",
      ],
      stackTitle: "Technical tools",
      stack: [
        { g: "Local", items: ["ComfyUI (RTX 4080 SUPER)", "Custom LoRA / LoKr / SDXL / Flux", "ACE-Step (audio AI)"] },
        { g: "Live event", items: ["disguise media-server", "Notch", "Resolume", "TouchDesigner (incl. MCP)"] },
        { g: "Image & video", items: ["Runway ML · Kling · Google Veo", "fal.ai · Nanobanana · Ideogram", "Adobe suite"] },
      ],
      whatTitle: "Where you'll find me",
      what: [
        { n: "—", t: "PoCo Experience", d: "Professional immersive event tech" },
        { n: "—", t: "Lectures at art schools", d: "AI in art, for young people" },
        { n: "—", t: "Freelance", d: "Estonia & Nordics" },
      ],
    },
    contact: {
      kicker: "Contact",
      title: "Intro call.",
      title2: "30 minutes.",
      title3: "Free.",
      lead: "What's your real need? Current workflow, pain points, volume, brand voice. If it's not a fit — I'll say so.",
      book: "Book in calendar",
      channels: [
        { l: "Email", v: "emer@example.ee" },
        { l: "LinkedIn", v: "linkedin.com/in/emervärk" },
        { l: "Instagram", v: "@emer.värk" },
      ],
      not: [
        "No Facebook Messenger",
        "No live-chat widget",
        "No «free download» popup",
      ],
      faq: [
        {
          q: "Does this work for marketers without an art background?",
          a: "Yes — the point of the training is to calibrate the marketer's eye. You don't have to become an artist, but you'll be able to tell why one AI image works and another doesn't.",
        },
        {
          q: "Do you also teach ChatGPT and writing?",
          a: "Only as far as it supports a visual workflow. For general ChatGPT training I recommend AI Eesti or Kasulik AI.",
        },
        {
          q: "Which tools do you teach?",
          a: "Depends on your need. Typically: ComfyUI for local work, Midjourney / Flux / Nanobanana for stills, Runway / Kling / Veo for video, Ideogram for typography images.",
        },
        {
          q: "In Estonian or English?",
          a: "Both. Usually Estonian in Estonia, English in the Nordics.",
        },
        {
          q: "Do you also do production, not just training?",
          a: "I'm primarily a production person who also teaches. Larger production projects through PoCo Experience.",
        },
      ],
    },
    foot: {
      colophon: "Image language and code —",
      author: "Emer Värk, 2026",
      tech: "ET · EN · monospace · no Google Analytics",
    },
  },
};
